name: Lint

on:
 pull_request:
    paths:
      - lib/**.lua
 push:
    branches:
    - master
    - release/*
    paths:
      - lib/**.lua


jobs:
  tests:
    name: Lint
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: Jayrgo/luacheck-action@01594c6841054ef52fe52c0711b1a9159df3b461 # v1.0.0
      name: luacheck
      with:
        # List of files, directories and rockspecs to check.
        # Default: .
        files: 'lib'

        # Path to configuration file.
        # Default: .luacheckrc
        config: '.luacheckrc'

        # Arguments passed to luacheck.
        # Default: -q
        args: '-q'
